### ISSUE TITLE
[Mbed-OS 5.13 OOB] Failed to compile with IAR 8.32

### ISSUE THREAD

**Issue by soleilplanet** [ARMmbed/mbed-os-example-crash-reporting#20] opened 2019-06-11 04:25 UTC
Failed to compile with IAR 8.32, fail log:

Link: mbed-os-example-crash-reporting
Elf2Bin: mbed-os-example-crash-reporting
[ERROR] 'cp950' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
[mbed] ERROR: "c:\python36\python.exe" returned error.
       Code: 1
       Path: "c:\Git\OOB\mbed-os-example-crash-reporting"
       Command: "c:\python36\python.exe -u c:\Git\OOB\mbed-os-example-crash-reporting\mbed-os\tools\make.py -t IAR -m K64F --source . --build .\BUILD\K64F\IAR"
       Tip: You could retry the last command with "-v" flag for verbose output
---
[mbed] WARNING: Using Python 3 with Mbed OS 5.8 and earlier can cause errors with compiling, testing and exporting

Reference info: issue compilation succeeded with GCC and ARMCC 6.11

**Comment by evedon** [comment] 2019-06-11 13:28
This works for me using python 2.7 on Linux machine.

Command : mbed compile -m K64F -t IAR
Output:
```
Link: mbed-os-example-crash-reporting
Link: /usr/local/iccarm-8.32/bin/ilinkarm -f ./BUILD/K64F/IAR/.link_options.txt
[DEBUG] Return: 0
[DEBUG] Output:
[DEBUG] Output:    IAR ELF Linker V8.32.1.169/LNX for ARM
[DEBUG] Output:    Copyright 2007-2018 IAR Systems AB.
[DEBUG] Output:
[DEBUG] Output:   35 394 bytes of readonly  code memory
[DEBUG] Output:    5 266 bytes of readonly  data memory
[DEBUG] Output:   75 217 bytes of readwrite data memory
[DEBUG] Output:
[DEBUG] Output: Errors: none
[DEBUG] Output: Warnings: none
[DEBUG] Output:
[DEBUG] Output: Link time:   0.30 (CPU)   0.30 (elapsed)
Elf2Bin: mbed-os-example-crash-reporting
FromELF: /usr/local/iccarm-8.32/bin/ielftool --bin ./BUILD/K64F/IAR/mbed-os-example-crash-reporting.elf ./BUILD/K64F/IAR/mbed-os-example-crash-reporting.bin
[DEBUG] Return: 0
[DEBUG] Output:
[DEBUG] Output:    IAR ELF Tool V10.4.6.1115 [BUILT locally]
[DEBUG] Output:    Copyright 2007-2018 IAR Systems AB.
[DEBUG] Output:
[DEBUG] Output: Loading ./BUILD/K64F/IAR/mbed-os-example-crash-reporting.elf
[DEBUG] Output: Saving binary file to ./BUILD/K64F/IAR/mbed-os-example-crash-reporting.bin
| Module               |         .text |     .data |        .bss |
|----------------------|---------------|-----------|-------------|
| [lib]/dl7M_tlf.a     | 10424(+10424) | 304(+304) |   700(+700) |
| [lib]/dlpp7M_tl_fc.a |       84(+84) |     0(+0) |       0(+0) |
| [lib]/m7M_tls.a      |   2298(+2298) |     0(+0) |       0(+0) |
| [lib]/rt7M_tl.a      |   1514(+1514) |     0(+0) |       0(+0) |
| [lib]/th7M_tlf.a     |     276(+276) |     0(+0) |     16(+16) |
| [misc]               |     272(+272) |     0(+0) |       0(+0) |
| main.o               |     672(+672) |     0(+0) |   152(+152) |
| mbed-os/cmsis        |   1024(+1024) |     0(+0) |       0(+0) |
| mbed-os/features     |       30(+30) |     0(+0) |   184(+184) |
| mbed-os/hal          |   1556(+1556) |     4(+4) |     66(+66) |
| mbed-os/platform     |   3978(+3978) | 144(+144) |   201(+201) |
| mbed-os/rtos         |   8204(+8204) | 168(+168) | 6325(+6325) |
| mbed-os/targets      | 10274(+10274) |   20(+20) |   373(+373) |
| Subtotals            | 40606(+40606) | 640(+640) | 8017(+8017) |
Total Static RAM memory (data + bss): 8657(+8657) bytes
Total Flash memory (text + data): 41246(+41246) bytes

Image: ./BUILD/K64F/IAR/mbed-os-example-crash-reporting.bin
```

**Comment by evedon** [comment] 2019-06-12 12:53
Also successfully tested using python 3.6 on Linux.

**Comment by zaphodikus** [comment] 2019-06-13 14:48
Hi Unable to reproduce this on Windows under python 2.7 and 3.6 - IAR 8.32 and was unable to reproduce this. Can you tell us anything unusual about your environment. Were you running the toolchain under dos or powershell prompt? Are you using any programs that may affect commandline?

**Comment by ConradBraam** [comment] 2019-06-13 15:01
Hi Unable to reproduce this on Windows under python 2.7 and 3.6 - IAR 8.32 and was unable to reproduce this. Can you tell us anything unusual about your environment. Were you running the toolchain under dos or powershell prompt? Are you using any programs that may affect commandline?

**Comment by ConradBraam** [comment] 2019-06-13 15:14
I also set a DOS console to codepage 950 (Which I am guessing is your default windows setup) and still built just fine.

**Comment by soleilplanet** [comment] 2019-06-14 16:52
Perhaps it's because I'm using a system with multi-byte charset by default?
I'm using normal console (DOS mode)
Attaching IAR8 verbose log, map and elf file below for your reference:
[mbed-os-example-crash-reporting-log-n-map.zip](https://github.com/ARMmbed/mbed-os-example-crash-reporting/files/3291620/mbed-os-example-crash-reporting-log-n-map.zip)
Also, I've tried a few more examples with IAR8 but all failed with the same error, but the same codes work with IAR7.

**Comment by soleilplanet** [comment] 2019-06-14 18:32
I modified the parse function in ./mbed-os/tools/memap.py to force it decode as UTF-8, and then IAR8 builds:
![image](https://user-images.githubusercontent.com/21167626/59530084-4d91d980-8f15-11e9-860f-34b8a7151b13.png)

So probably for some reason IAR8 generated something not decode-able in the map file in Windows which by default uses multi-byte charset

**Comment by ConradBraam** [comment] 2019-06-17 08:56
The Jira integration appears to not be creating a ticket. Alvin, can you raise a ticket manually, sounds like this needs some configuration support and is not a straightforward change. 
Would like a broader experience person to look at this before trying to make a fix for just one place which may even be broken in other places, because it might be possible to solve, another way. For me IAR writing a file explicitly as UTF8 (without a BOM mark), while other tools are maybe not writing a BOM. It's runtime probeable, but lets track in a ticket.

**Comment by adbridge** [comment] 2019-06-17 10:34
IS this a compiler issue or a tools issue . If the latter IOTTOOLS is probably the place

**Comment by adbridge** [comment] 2019-06-17 10:36
This example is not being mirrored to Jira! Probably because the creator did not think to add / ask for it :(

**Comment by adbridge** [comment] 2019-06-17 10:36
I'll add it in now

**Comment by mark-edgeworth** [comment] 2019-06-18 08:34
Thanks for the info here. I've seen quite a few issues related to encoding in the tools recently. We'll have to take a wider look. FYI the issue is mirrored now in IOTBTOOL-306

**Comment by ConradBraam** [comment] 2019-06-18 09:37
confirm , simply adding , "--text_out utf8", "--no_bom" to the linker options for iar in all profiles should resolve this. 
for example your last 3 lines in tools\profiles\develop.json profile needs to look like
        "ld": ["--skip_dynamic_initialization", "--threaded_lib", "--text_out utf8", "--no_bom"]
    }
}
Would need to verify that this parameter does not break IAR 7.X

**Comment by adbridge** [comment] 2019-06-18 13:41
Closing this one now that there is an issue in the tools to look at this.

**Closed as completed by adbridge** 2019-06-18 13:41 UTC
